/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cokomo.CokomoApiClient.Client;
using Cokomo.CokomoApiClient.Api;
// uncomment below to import models
//using Cokomo.CokomoApiClient.Model;

namespace Cokomo.CokomoApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing CompetenceBaseApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CompetenceBaseApiTests : IDisposable
    {
        private CompetenceBaseApi instance;

        public CompetenceBaseApiTests()
        {
            instance = new CompetenceBaseApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompetenceBaseApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CompetenceBaseApi
            //Assert.IsType<CompetenceBaseApi>(instance);
        }

        /// <summary>
        /// Test CompetenceBaseIdDetailsGet
        /// </summary>
        [Fact]
        public void CompetenceBaseIdDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.CompetenceBaseIdDetailsGet(id);
            //Assert.IsType<CompetenceBase>(response);
        }

        /// <summary>
        /// Test CompetenceBaseIdGet
        /// </summary>
        [Fact]
        public void CompetenceBaseIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.CompetenceBaseIdGet(id);
            //Assert.IsType<CompetenceBase>(response);
        }

        /// <summary>
        /// Test CompetenceBaseIdNeighboursGet
        /// </summary>
        [Fact]
        public void CompetenceBaseIdNeighboursGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? depth = null;
            //var response = instance.CompetenceBaseIdNeighboursGet(id, depth);
            //Assert.IsType<Neighbour>(response);
        }
    }
}
