/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cokomo.CokomoApiClient.Client;
using Cokomo.CokomoApiClient.Api;
// uncomment below to import models
//using Cokomo.CokomoApiClient.Model;

namespace Cokomo.CokomoApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing LearningGoalApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LearningGoalApiTests : IDisposable
    {
        private LearningGoalApi instance;

        public LearningGoalApiTests()
        {
            instance = new LearningGoalApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LearningGoalApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LearningGoalApi
            //Assert.IsType<LearningGoalApi>(instance);
        }

        /// <summary>
        /// Test LearningGoalIdDetailsGet
        /// </summary>
        [Fact]
        public void LearningGoalIdDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.LearningGoalIdDetailsGet(id);
            //Assert.IsType<LearningGoal>(response);
        }

        /// <summary>
        /// Test LearningGoalIdGet
        /// </summary>
        [Fact]
        public void LearningGoalIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.LearningGoalIdGet(id);
            //Assert.IsType<LearningGoal>(response);
        }
    }
}
