/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cokomo.CokomoApiClient.Client;
using Cokomo.CokomoApiClient.Api;
// uncomment below to import models
//using Cokomo.CokomoApiClient.Model;

namespace Cokomo.CokomoApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing MetamodelApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MetamodelApiTests : IDisposable
    {
        private MetamodelApi instance;

        public MetamodelApiTests()
        {
            instance = new MetamodelApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetamodelApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MetamodelApi
            //Assert.IsType<MetamodelApi>(instance);
        }

        /// <summary>
        /// Test MetamodelGet
        /// </summary>
        [Fact]
        public void MetamodelGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MetamodelGet();
            //Assert.IsType<Metamodel>(response);
        }
    }
}
