/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CompetenceLevel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompetenceLevelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompetenceLevel
        //private CompetenceLevel instance;

        public CompetenceLevelTests()
        {
            // TODO uncomment below to create an instance of CompetenceLevel
            //instance = new CompetenceLevel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompetenceLevel
        /// </summary>
        [Fact]
        public void CompetenceLevelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompetenceLevel
            //Assert.IsType<CompetenceLevel>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
    }
}
