/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing EdgeType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdgeTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdgeType
        //private EdgeType instance;

        public EdgeTypeTests()
        {
            // TODO uncomment below to create an instance of EdgeType
            //instance = new EdgeType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdgeType
        /// </summary>
        [Fact]
        public void EdgeTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdgeType
            //Assert.IsType<EdgeType>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Abbreviation'
        /// </summary>
        [Fact]
        public void AbbreviationTest()
        {
            // TODO unit test for the property 'Abbreviation'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
