/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing LearningGoal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LearningGoalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LearningGoal
        //private LearningGoal instance;

        public LearningGoalTests()
        {
            // TODO uncomment below to create an instance of LearningGoal
            //instance = new LearningGoal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LearningGoal
        /// </summary>
        [Fact]
        public void LearningGoalInstanceTest()
        {
            // TODO uncomment below to test "IsType" LearningGoal
            //Assert.IsType<LearningGoal>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'UnderlyingCompetenceBase'
        /// </summary>
        [Fact]
        public void UnderlyingCompetenceBaseTest()
        {
            // TODO unit test for the property 'UnderlyingCompetenceBase'
        }

        /// <summary>
        /// Test the property 'AssociatedCompetenceLevel'
        /// </summary>
        [Fact]
        public void AssociatedCompetenceLevelTest()
        {
            // TODO unit test for the property 'AssociatedCompetenceLevel'
        }
    }
}
