/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Metamodel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetamodelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Metamodel
        //private Metamodel instance;

        public MetamodelTests()
        {
            // TODO uncomment below to create an instance of Metamodel
            //instance = new Metamodel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Metamodel
        /// </summary>
        [Fact]
        public void MetamodelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Metamodel
            //Assert.IsType<Metamodel>(instance);
        }

        /// <summary>
        /// Test the property 'CompetenceBaseTypes'
        /// </summary>
        [Fact]
        public void CompetenceBaseTypesTest()
        {
            // TODO unit test for the property 'CompetenceBaseTypes'
        }

        /// <summary>
        /// Test the property 'EdgeTypes'
        /// </summary>
        [Fact]
        public void EdgeTypesTest()
        {
            // TODO unit test for the property 'EdgeTypes'
        }
    }
}
