/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Neighbour
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NeighbourTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Neighbour
        //private Neighbour instance;

        public NeighbourTests()
        {
            // TODO uncomment below to create an instance of Neighbour
            //instance = new Neighbour();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Neighbour
        /// </summary>
        [Fact]
        public void NeighbourInstanceTest()
        {
            // TODO uncomment below to test "IsType" Neighbour
            //Assert.IsType<Neighbour>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Fact]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Relation'
        /// </summary>
        [Fact]
        public void RelationTest()
        {
            // TODO unit test for the property 'Relation'
        }

        /// <summary>
        /// Test the property 'Neighbours'
        /// </summary>
        [Fact]
        public void NeighboursTest()
        {
            // TODO unit test for the property 'Neighbours'
        }
    }
}
