/*
 * Cokomo Public Api
 *
 * Public API Documentation for Cokomo system
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cokomo.CokomoApiClient.Model;
using Cokomo.CokomoApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cokomo.CokomoApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing NeighbourEdge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NeighbourEdgeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NeighbourEdge
        //private NeighbourEdge instance;

        public NeighbourEdgeTests()
        {
            // TODO uncomment below to create an instance of NeighbourEdge
            //instance = new NeighbourEdge();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NeighbourEdge
        /// </summary>
        [Fact]
        public void NeighbourEdgeInstanceTest()
        {
            // TODO uncomment below to test "IsType" NeighbourEdge
            //Assert.IsType<NeighbourEdge>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
    }
}
